#!/bin/bash

export COURIER_AWS_ACCESS_KEY_ID="AKIAWSRWE3IHR2AC6RVF"
export COURIER_AWS_SECRET_ACCESS_KEY="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"
export COURIER_S3_REGION="us-west-1"
export COURIER_LOG_LEVEL="debug"
